In [1]:
import networkx
import numpy as np
import pickle

In [2]:
from utils import load_data

In [3]:
labels_cora = load_data('cora')

In [10]:
def save_labels(dataset_name):
    labels = load_data(dataset_name)
    #f = open(dataset_name+"_proper_v2.labels","wb")
    #pickle.dump(labels,f,protocol=2)
    print(type(labels))
    
for i in ['cora','pubmed','citeseer']:
    save_labels(i)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 0 0 1]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 0 0 1]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 0 0 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 0]
[0 0 0 1 0 0 0]
[1 0 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0

array([0., 0., 0., 0., 1., 0., 0.])

In [27]:
for i in range(len(val_mask)):
    if val_mask[i]==True:
        print(f"for {i} - {y_val[i]}")

for 140 - [0. 0. 0. 0. 1. 0. 0.]
for 141 - [0. 0. 0. 1. 0. 0. 0.]
for 142 - [1. 0. 0. 0. 0. 0. 0.]
for 143 - [0. 0. 0. 1. 0. 0. 0.]
for 144 - [0. 0. 0. 0. 0. 0. 1.]
for 145 - [0. 0. 0. 0. 0. 0. 1.]
for 146 - [1. 0. 0. 0. 0. 0. 0.]
for 147 - [0. 0. 0. 1. 0. 0. 0.]
for 148 - [0. 0. 0. 0. 1. 0. 0.]
for 149 - [1. 0. 0. 0. 0. 0. 0.]
for 150 - [0. 0. 0. 1. 0. 0. 0.]
for 151 - [0. 0. 0. 0. 1. 0. 0.]
for 152 - [0. 0. 0. 0. 1. 0. 0.]
for 153 - [0. 1. 0. 0. 0. 0. 0.]
for 154 - [0. 0. 1. 0. 0. 0. 0.]
for 155 - [0. 0. 1. 0. 0. 0. 0.]
for 156 - [0. 0. 1. 0. 0. 0. 0.]
for 157 - [0. 0. 0. 1. 0. 0. 0.]
for 158 - [0. 0. 0. 1. 0. 0. 0.]
for 159 - [0. 0. 0. 1. 0. 0. 0.]
for 160 - [0. 0. 0. 1. 0. 0. 0.]
for 161 - [1. 0. 0. 0. 0. 0. 0.]
for 162 - [0. 0. 0. 0. 1. 0. 0.]
for 163 - [0. 0. 0. 0. 0. 1. 0.]
for 164 - [1. 0. 0. 0. 0. 0. 0.]
for 165 - [0. 0. 0. 1. 0. 0. 0.]
for 166 - [0. 0. 0. 0. 1. 0. 0.]
for 167 - [0. 0. 0. 1. 0. 0. 0.]
for 168 - [0. 0. 0. 1. 0. 0. 0.]
for 169 - [0. 0. 0. 1. 0. 0. 0.]
for 170 - 

In [28]:
for i in range(len(test_mask)):
    if test_mask[i]==True:
        print(f"for {i} - {y_test[i]}")

for 1708 - [0. 0. 0. 1. 0. 0. 0.]
for 1709 - [0. 0. 1. 0. 0. 0. 0.]
for 1710 - [0. 0. 1. 0. 0. 0. 0.]
for 1711 - [0. 0. 1. 0. 0. 0. 0.]
for 1712 - [0. 0. 1. 0. 0. 0. 0.]
for 1713 - [1. 0. 0. 0. 0. 0. 0.]
for 1714 - [0. 0. 1. 0. 0. 0. 0.]
for 1715 - [0. 0. 1. 0. 0. 0. 0.]
for 1716 - [0. 0. 1. 0. 0. 0. 0.]
for 1717 - [0. 0. 1. 0. 0. 0. 0.]
for 1718 - [0. 0. 1. 0. 0. 0. 0.]
for 1719 - [0. 0. 1. 0. 0. 0. 0.]
for 1720 - [0. 0. 1. 0. 0. 0. 0.]
for 1721 - [0. 0. 1. 0. 0. 0. 0.]
for 1722 - [0. 0. 1. 0. 0. 0. 0.]
for 1723 - [0. 0. 1. 0. 0. 0. 0.]
for 1724 - [0. 0. 1. 0. 0. 0. 0.]
for 1725 - [0. 0. 1. 0. 0. 0. 0.]
for 1726 - [0. 0. 1. 0. 0. 0. 0.]
for 1727 - [0. 0. 1. 0. 0. 0. 0.]
for 1728 - [0. 0. 0. 1. 0. 0. 0.]
for 1729 - [0. 0. 1. 0. 0. 0. 0.]
for 1730 - [0. 0. 1. 0. 0. 0. 0.]
for 1731 - [0. 0. 1. 0. 0. 0. 0.]
for 1732 - [0. 0. 1. 0. 0. 0. 0.]
for 1733 - [0. 0. 1. 0. 0. 0. 0.]
for 1734 - [0. 0. 1. 0. 0. 0. 0.]
for 1735 - [0. 1. 0. 0. 0. 0. 0.]
for 1736 - [0. 0. 1. 0. 0. 0. 0.]
for 1737 - [0.

In [29]:
for i in range(len(train_mask)):
    if train_mask[i]==True:
        print(f"for {i} - {y_train[i]}")

for 0 - [0. 0. 0. 1. 0. 0. 0.]
for 1 - [0. 0. 0. 0. 1. 0. 0.]
for 2 - [0. 0. 0. 0. 1. 0. 0.]
for 3 - [1. 0. 0. 0. 0. 0. 0.]
for 4 - [0. 0. 0. 1. 0. 0. 0.]
for 5 - [0. 0. 1. 0. 0. 0. 0.]
for 6 - [1. 0. 0. 0. 0. 0. 0.]
for 7 - [0. 0. 0. 1. 0. 0. 0.]
for 8 - [0. 0. 0. 1. 0. 0. 0.]
for 9 - [0. 0. 1. 0. 0. 0. 0.]
for 10 - [1. 0. 0. 0. 0. 0. 0.]
for 11 - [1. 0. 0. 0. 0. 0. 0.]
for 12 - [0. 0. 0. 0. 1. 0. 0.]
for 13 - [0. 0. 0. 1. 0. 0. 0.]
for 14 - [0. 0. 0. 1. 0. 0. 0.]
for 15 - [0. 0. 0. 1. 0. 0. 0.]
for 16 - [0. 0. 1. 0. 0. 0. 0.]
for 17 - [0. 0. 0. 1. 0. 0. 0.]
for 18 - [0. 1. 0. 0. 0. 0. 0.]
for 19 - [0. 0. 0. 1. 0. 0. 0.]
for 20 - [0. 0. 0. 0. 0. 1. 0.]
for 21 - [0. 0. 0. 1. 0. 0. 0.]
for 22 - [0. 0. 0. 0. 1. 0. 0.]
for 23 - [0. 0. 0. 0. 0. 0. 1.]
for 24 - [0. 0. 0. 1. 0. 0. 0.]
for 25 - [0. 0. 0. 1. 0. 0. 0.]
for 26 - [0. 0. 0. 0. 0. 0. 1.]
for 27 - [0. 0. 0. 1. 0. 0. 0.]
for 28 - [0. 0. 1. 0. 0. 0. 0.]
for 29 - [0. 0. 0. 0. 1. 0. 0.]
for 30 - [0. 0. 0. 1. 0. 0. 0.]
for 31 - [0. 0. 0.

In [30]:
adj1, features1, y_train1, y_val1, y_test1, train_mask1, val_mask1, test_mask1 = load_data('pubmed')

In [32]:
new_arr1 = np.zeros(y_train1.shape)
new_arr1[train_mask1]=y_train1[train_mask1]
new_arr1[val_mask1]=y_val1[val_mask1]
new_arr1[test_mask1]=y_test1[test_mask1]

In [38]:
new_arr1[25]

array([0., 1., 0.])

In [40]:
for i in range(50,65):
    print(new_arr1[i])

[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[0. 0. 1.]
[0. 0. 1.]
[0. 1. 0.]
[0. 0. 1.]
[0. 1. 0.]
